// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BrokerMessage struct {
	Source               string         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Targets              []string       `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	SourceMessage        *SourceMessage `protobuf:"bytes,3,opt,name=sourceMessage,proto3" json:"sourceMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BrokerMessage) Reset()         { *m = BrokerMessage{} }
func (m *BrokerMessage) String() string { return proto.CompactTextString(m) }
func (*BrokerMessage) ProtoMessage()    {}
func (*BrokerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_c4b2c82165967e7b, []int{0}
}
func (m *BrokerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerMessage.Unmarshal(m, b)
}
func (m *BrokerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerMessage.Marshal(b, m, deterministic)
}
func (dst *BrokerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerMessage.Merge(dst, src)
}
func (m *BrokerMessage) XXX_Size() int {
	return xxx_messageInfo_BrokerMessage.Size(m)
}
func (m *BrokerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerMessage proto.InternalMessageInfo

func (m *BrokerMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *BrokerMessage) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *BrokerMessage) GetSourceMessage() *SourceMessage {
	if m != nil {
		return m.SourceMessage
	}
	return nil
}

type TargetMessage struct {
	Target               string         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source               string         `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceMessage        *SourceMessage `protobuf:"bytes,3,opt,name=sourceMessage,proto3" json:"sourceMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TargetMessage) Reset()         { *m = TargetMessage{} }
func (m *TargetMessage) String() string { return proto.CompactTextString(m) }
func (*TargetMessage) ProtoMessage()    {}
func (*TargetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_c4b2c82165967e7b, []int{1}
}
func (m *TargetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetMessage.Unmarshal(m, b)
}
func (m *TargetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetMessage.Marshal(b, m, deterministic)
}
func (dst *TargetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetMessage.Merge(dst, src)
}
func (m *TargetMessage) XXX_Size() int {
	return xxx_messageInfo_TargetMessage.Size(m)
}
func (m *TargetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TargetMessage proto.InternalMessageInfo

func (m *TargetMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *TargetMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TargetMessage) GetSourceMessage() *SourceMessage {
	if m != nil {
		return m.SourceMessage
	}
	return nil
}

type SourceMessage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              []byte            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SourceMessage) Reset()         { *m = SourceMessage{} }
func (m *SourceMessage) String() string { return proto.CompactTextString(m) }
func (*SourceMessage) ProtoMessage()    {}
func (*SourceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_c4b2c82165967e7b, []int{2}
}
func (m *SourceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceMessage.Unmarshal(m, b)
}
func (m *SourceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceMessage.Marshal(b, m, deterministic)
}
func (dst *SourceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceMessage.Merge(dst, src)
}
func (m *SourceMessage) XXX_Size() int {
	return xxx_messageInfo_SourceMessage.Size(m)
}
func (m *SourceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SourceMessage proto.InternalMessageInfo

func (m *SourceMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SourceMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SourceMessage) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*BrokerMessage)(nil), "message.BrokerMessage")
	proto.RegisterType((*TargetMessage)(nil), "message.TargetMessage")
	proto.RegisterType((*SourceMessage)(nil), "message.SourceMessage")
	proto.RegisterMapType((map[string]string)(nil), "message.SourceMessage.MetaEntry")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_protobuf_c4b2c82165967e7b) }

var fileDescriptor_protobuf_c4b2c82165967e7b = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x03, 0x33, 0x84, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53,
	0x95, 0xea, 0xb9, 0x78, 0x9d, 0x8a, 0xf2, 0xb3, 0x53, 0x8b, 0x7c, 0x21, 0x02, 0x42, 0x62, 0x5c,
	0x6c, 0xc5, 0xf9, 0xa5, 0x45, 0xc9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e,
	0x90, 0x04, 0x17, 0x7b, 0x49, 0x62, 0x51, 0x7a, 0x6a, 0x49, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06,
	0x67, 0x10, 0x8c, 0x2b, 0x64, 0xc3, 0xc5, 0x0b, 0x51, 0x03, 0x35, 0x42, 0x82, 0x59, 0x81, 0x51,
	0x83, 0xdb, 0x48, 0x4c, 0x0f, 0x6a, 0x87, 0x5e, 0x30, 0xb2, 0x6c, 0x10, 0xaa, 0x62, 0xa5, 0x5a,
	0x2e, 0xde, 0x10, 0xb0, 0x41, 0x48, 0x0e, 0x80, 0x98, 0x0c, 0x73, 0x00, 0x84, 0x87, 0xe4, 0x30,
	0x26, 0x14, 0x87, 0x51, 0x66, 0xfd, 0x0a, 0x46, 0x2e, 0x5e, 0x14, 0x05, 0x42, 0x7c, 0x5c, 0x4c,
	0x99, 0x29, 0x50, 0xbb, 0x99, 0x32, 0x53, 0x40, 0x1e, 0x87, 0x9a, 0x04, 0xb6, 0x98, 0x27, 0x08,
	0xc6, 0x15, 0x32, 0xe1, 0x62, 0xc9, 0x4d, 0x2d, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x36,
	0x52, 0xc0, 0x6e, 0xa1, 0x9e, 0x6f, 0x6a, 0x49, 0xa2, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x58,
	0xb5, 0x94, 0x39, 0x17, 0x27, 0x5c, 0x48, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0x6a, 0x1b,
	0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x0a, 0xf3, 0x25, 0x84, 0x63, 0xc5, 0x64,
	0xc1, 0x98, 0xc4, 0x06, 0x8e, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x8e, 0x6c,
	0x68, 0xcc, 0x01, 0x00, 0x00,
}
