// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BrokerMessage struct {
	Source               string         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Targets              []string       `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	SourceMessage        *SourceMessage `protobuf:"bytes,3,opt,name=sourceMessage,proto3" json:"sourceMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BrokerMessage) Reset()         { *m = BrokerMessage{} }
func (m *BrokerMessage) String() string { return proto.CompactTextString(m) }
func (*BrokerMessage) ProtoMessage()    {}
func (*BrokerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_467c93ab2ed3abdc, []int{0}
}
func (m *BrokerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerMessage.Unmarshal(m, b)
}
func (m *BrokerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerMessage.Marshal(b, m, deterministic)
}
func (dst *BrokerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerMessage.Merge(dst, src)
}
func (m *BrokerMessage) XXX_Size() int {
	return xxx_messageInfo_BrokerMessage.Size(m)
}
func (m *BrokerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerMessage proto.InternalMessageInfo

func (m *BrokerMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *BrokerMessage) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *BrokerMessage) GetSourceMessage() *SourceMessage {
	if m != nil {
		return m.SourceMessage
	}
	return nil
}

type TargetMessage struct {
	Target               string         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source               string         `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceMessage        *SourceMessage `protobuf:"bytes,3,opt,name=sourceMessage,proto3" json:"sourceMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TargetMessage) Reset()         { *m = TargetMessage{} }
func (m *TargetMessage) String() string { return proto.CompactTextString(m) }
func (*TargetMessage) ProtoMessage()    {}
func (*TargetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_467c93ab2ed3abdc, []int{1}
}
func (m *TargetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetMessage.Unmarshal(m, b)
}
func (m *TargetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetMessage.Marshal(b, m, deterministic)
}
func (dst *TargetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetMessage.Merge(dst, src)
}
func (m *TargetMessage) XXX_Size() int {
	return xxx_messageInfo_TargetMessage.Size(m)
}
func (m *TargetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TargetMessage proto.InternalMessageInfo

func (m *TargetMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *TargetMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TargetMessage) GetSourceMessage() *SourceMessage {
	if m != nil {
		return m.SourceMessage
	}
	return nil
}

type SourceMessage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              []byte            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Attributes           *Attributes       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SourceMessage) Reset()         { *m = SourceMessage{} }
func (m *SourceMessage) String() string { return proto.CompactTextString(m) }
func (*SourceMessage) ProtoMessage()    {}
func (*SourceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_467c93ab2ed3abdc, []int{2}
}
func (m *SourceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceMessage.Unmarshal(m, b)
}
func (m *SourceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceMessage.Marshal(b, m, deterministic)
}
func (dst *SourceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceMessage.Merge(dst, src)
}
func (m *SourceMessage) XXX_Size() int {
	return xxx_messageInfo_SourceMessage.Size(m)
}
func (m *SourceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SourceMessage proto.InternalMessageInfo

func (m *SourceMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SourceMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SourceMessage) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SourceMessage) GetAttributes() *Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Attributes struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobuf_467c93ab2ed3abdc, []int{3}
}
func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (dst *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(dst, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Attributes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*BrokerMessage)(nil), "message.BrokerMessage")
	proto.RegisterType((*TargetMessage)(nil), "message.TargetMessage")
	proto.RegisterType((*SourceMessage)(nil), "message.SourceMessage")
	proto.RegisterMapType((map[string]string)(nil), "message.SourceMessage.MetaEntry")
	proto.RegisterType((*Attributes)(nil), "message.Attributes")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_protobuf_467c93ab2ed3abdc) }

var fileDescriptor_protobuf_467c93ab2ed3abdc = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0xa6, 0x7f, 0x4b, 0x6e, 0xff, 0x14, 0xb9, 0x4a, 0x19, 0xc4, 0x45, 0xc8, 0x2a,
	0xab, 0x2c, 0x5a, 0x41, 0x11, 0x11, 0x14, 0x5c, 0x76, 0x33, 0xfa, 0x02, 0x13, 0x3b, 0x96, 0x50,
	0x63, 0xc2, 0xcc, 0x8d, 0x90, 0x85, 0xf8, 0xa4, 0xbe, 0x8b, 0x74, 0x32, 0x49, 0x13, 0x70, 0xe7,
	0xee, 0x9e, 0x99, 0x73, 0xbf, 0x73, 0x12, 0x06, 0x16, 0x95, 0x2e, 0xa9, 0xcc, 0xea, 0xd7, 0xd4,
	0x0e, 0x38, 0x2b, 0x94, 0x31, 0x72, 0xa7, 0xe2, 0x2f, 0x08, 0x1f, 0x74, 0xb9, 0x57, 0x7a, 0xd3,
	0x1e, 0xe0, 0x12, 0xa6, 0xa6, 0xac, 0xf5, 0x8b, 0xe2, 0x5e, 0xe4, 0x25, 0x81, 0x70, 0x0a, 0x39,
	0xcc, 0x48, 0xea, 0x9d, 0x22, 0xc3, 0xfd, 0x88, 0x25, 0x81, 0xe8, 0x24, 0xde, 0x42, 0xd8, 0x7a,
	0x1c, 0x82, 0xb3, 0xc8, 0x4b, 0xe6, 0xab, 0x65, 0xea, 0x32, 0xd2, 0xa7, 0xe1, 0xad, 0x18, 0x9b,
	0xe3, 0x4f, 0x08, 0x9f, 0x2d, 0x68, 0x50, 0xa0, 0x25, 0x77, 0x05, 0x5a, 0x35, 0x28, 0xe6, 0x8f,
	0x8a, 0xfd, 0x2d, 0xfe, 0xdb, 0x83, 0x70, 0x64, 0xc0, 0x05, 0xf8, 0xf9, 0xd6, 0x65, 0xfb, 0xf9,
	0xf6, 0xf0, 0xe1, 0x8e, 0x64, 0x83, 0xff, 0x8b, 0x4e, 0xe2, 0x25, 0x4c, 0x0a, 0x45, 0x92, 0xb3,
	0x88, 0x25, 0xf3, 0x55, 0xf4, 0x7b, 0x60, 0xba, 0x51, 0x24, 0x1f, 0xdf, 0x49, 0x37, 0xc2, 0xba,
	0x71, 0x0d, 0x20, 0x89, 0x74, 0x9e, 0xd5, 0xa4, 0x0c, 0x9f, 0xd8, 0xb2, 0xa7, 0xfd, 0xee, 0x7d,
	0x7f, 0x25, 0x06, 0xb6, 0xf3, 0x2b, 0x08, 0x7a, 0x0e, 0x9e, 0x00, 0xdb, 0xab, 0xc6, 0x55, 0x3c,
	0x8c, 0x78, 0x06, 0xff, 0x3e, 0xe4, 0x5b, 0xdd, 0xfd, 0x9a, 0x56, 0xdc, 0xf8, 0xd7, 0x5e, 0x7c,
	0x07, 0x70, 0x44, 0xe2, 0x05, 0x04, 0x94, 0x17, 0xca, 0x90, 0x2c, 0x2a, 0xbb, 0xcf, 0xc4, 0xf1,
	0x00, 0x11, 0x26, 0xd4, 0x54, 0x1d, 0xc4, 0xce, 0xd9, 0xd4, 0xbe, 0x97, 0xf5, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xff, 0x4b, 0xa0, 0x41, 0x02, 0x00, 0x00,
}
